/******************************************************************************
Copyright (c) 2013-2014, Altera Corporation.  All rights reserved.

Redistribution and use of this software, in source and binary code forms, with or without modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

3. Neither the name of Altera Corporation nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

4. This software may only be used to run on Altera products, or to program Altera devices.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF THE COPYRIGHT HOLDERS OR CONTRIBUTORS ARE ADVISED OF THE POSSIBILITY DAMAGE IS LIKELY TO OCCUR.
******************************************************************************/
#include <core.h>
#include <trustzone.h>
#include <scu.h>
#include "socal/alt_sdr.h"

#define ALT_MPUSCU_NSAC_OFFSET            0x54
#define ALT_MPUSCU_NSAC_GLOBAL_NONSECURE  0xF00
#define ALT_MPUSCU_NSAC_PRIVATE_NONSECURE 0x0F0

#define ALT_SDR_CTL_OFST                      0x5000
#define ALT_SDR_CTL_PROTRULEID_LOW(x)         (x)
#define ALT_SDR_CTL_PROTRULEID_HIGH(x)        ((x) << 12)
#define ALT_SDR_CTL_PROTRULEADDR_LOW(x)       ((x) >> 20)
#define ALT_SDR_CTL_PROTRULEADDR_HIGH(x)      (((x)-1)>>8) & (0xFFF << 12)
#define ALT_SDR_CTL_DATA_RULE_VALID           (1<<2)
#define ALT_SDR_CTL_DATA_RULE_INVALID         0
#define ALT_L3_SEC_OFST                       8

uint32 ruleInUse[MAX_RULE_NUM] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};

uint32  alt_sdr_ctl_set_tz_rule(uint32 RuleNum, uint32 LowAddr, uint32 HighAddr, uint32 RuleMin, uint32 RuleMax,
	uint32 SecurityType, uint32 Ports, uint32 AccessPermission)
{
  volatile ALT_SDR_CTL_raw_t *sdr = (ALT_SDR_CTL_raw_t *)(ALT_SDR_OFST + ALT_SDR_CTL_OFST);
  if(RuleNum == ALT_SDR_CTL_RULE_NEW)
  {
    for(RuleNum=0; RuleNum<MAX_RULE_NUM; RuleNum++)
      if(ruleInUse[RuleNum] == 0)
        break;
    if(MAX_RULE_NUM == RuleNum)
      return   ALT_SDR_CTL_RULE_INVALID;
  }
  ruleInUse[RuleNum] = 1;
  sdr->protrulerdwr = ALT_SDR_CTL_PROTRULERDWR_RULEOFFSET_SET(RuleNum);
  sdr->protruleaddr = ALT_SDR_CTL_PROTRULEADDR_LOW(LowAddr) | ALT_SDR_CTL_PROTRULEADDR_HIGH(HighAddr);
  sdr->protruleid = ALT_SDR_CTL_PROTRULEID_LOW(RuleMin) | ALT_SDR_CTL_PROTRULEID_HIGH(RuleMax);
  sdr->protruledata = SecurityType | ALT_SDR_CTL_DATA_RULE_VALID |
	  Ports | AccessPermission;
  sdr->protrulerdwr = ALT_SDR_CTL_PROTRULERDWR_RULEOFFSET_SET(RuleNum) | ALT_SDR_CTL_PROTRULERDWR_WRITE;
  sdr->protrulerdwr = ALT_SDR_CTL_PROTRULERDWR_RULEOFFSET_SET(RuleNum);
  return RuleNum;
}

void    alt_sdr_ctl_delete_rule(uint32 RuleNum)
{
  volatile ALT_SDR_CTL_raw_t *sdr = (ALT_SDR_CTL_raw_t *)(ALT_SDR_OFST + ALT_SDR_CTL_OFST);
  sdr->protrulerdwr = ALT_SDR_CTL_PROTRULERDWR_RULEOFFSET_SET(RuleNum);
  sdr->protruledata = ALT_SDR_CTL_DATA_RULE_INVALID;
  sdr->protrulerdwr = ALT_SDR_CTL_PROTRULERDWR_RULEOFFSET_SET(RuleNum) | ALT_SDR_CTL_PROTRULERDWR_WRITE;
  sdr->protrulerdwr = ALT_SDR_CTL_PROTRULERDWR_RULEOFFSET_SET(RuleNum);
}

uint32  alt_sdr_ctl_set_tz_default(uint32 defaultRule)
{
  volatile ALT_SDR_CTL_raw_t *sdr = (ALT_SDR_CTL_raw_t *)(ALT_SDR_OFST + ALT_SDR_CTL_OFST);
  sdr->protportdefault = defaultRule;
}

#define INVERSE(x) (0xFFFFFFFF ^ (x))

void alt_l3_secgrp_set_peripheral_access(uint64 NonSecure, uint64 SecureOnly)
{
  volatile ALT_L3_SECGRP_raw_t *l3s = (ALT_L3_SECGRP_raw_t *) (ALT_L3_OFST + ALT_L3_SEC_OFST);
  volatile uint32 *scu_ns_p = (uint32 *) (ALT_MPUSCU_ADDR + ALT_MPUSCU_NSAC_OFFSET);

  uint32 main, main_o, l4sp, l4sp_o, l4mp, l4mp_o, l4osc1, l4osc1_o, l4spim, l4spim_o, scu_ns, scu_ns_o;
  main_o = main = l3s->l4main;
  l4sp_o = l4sp = l3s->l4sp;
  l4mp_o = l4mp = l3s->l4mp;
  l4osc1_o = l4osc1 = l3s->l4osc1;
  l4spim_o = l4spim = l3s->l4spim;
  scu_ns_o = scu_ns = *scu_ns_p;

  //?? There is a secure and a nonsecure dma device. What's this peripheral about?
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_DMA)
    main |= ALT_L3_SEC_L4MAIN_DMASECURE_SET(ALT_L3_SEC_L4MAIN_DMASECURE_E_NONSECURE);
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_DMA)
    main &= INVERSE(ALT_L3_SEC_L4MAIN_DMASECURE_SET(ALT_L3_SEC_L4MAIN_DMASECURE_E_NONSECURE));

  if(NonSecure & ALT_L3_SEC_PERIPHERAL_USB0)
    l3s->usb0 = ALT_L3_SEC_USB0_S_SET(ALT_L3_SEC_USB0_S_E_NONSECURE); 
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_USB0)
    l3s->usb0 = ALT_L3_SEC_USB0_S_SET(ALT_L3_SEC_USB0_S_E_SECURE); 

  if(NonSecure & ALT_L3_SEC_PERIPHERAL_USB1)
    l3s->usb1 = ALT_L3_SEC_USB1_S_SET(ALT_L3_SEC_USB1_S_E_NONSECURE); 
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_USB1)
    l3s->usb1 = ALT_L3_SEC_USB1_S_SET(ALT_L3_SEC_USB1_S_E_SECURE); 

  
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_CAN0)
    l4sp |= ALT_L3_SEC_L4SP_CAN0_SET(ALT_L3_SEC_L4SP_CAN0_E_NONSECURE);
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_CAN0)
    l4sp &= INVERSE(ALT_L3_SEC_L4SP_CAN0_SET(ALT_L3_SEC_L4SP_CAN0_E_NONSECURE));

  if(NonSecure & ALT_L3_SEC_PERIPHERAL_CAN1)
    l4sp |= ALT_L3_SEC_L4SP_CAN1_SET(ALT_L3_SEC_L4SP_CAN1_E_NONSECURE);
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_CAN1)
    l4sp &= INVERSE(ALT_L3_SEC_L4SP_CAN1_SET(ALT_L3_SEC_L4SP_CAN1_E_NONSECURE));

  if(NonSecure & ALT_L3_SEC_PERIPHERAL_SDMMC)
    l4mp |= ALT_L3_SEC_L4MP_SDMMC_SET(ALT_L3_SEC_L4MP_SDMMC_E_NONSECURE); 
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_SDMMC)
    l4mp &= INVERSE(ALT_L3_SEC_L4MP_SDMMC_SET(ALT_L3_SEC_L4MP_SDMMC_E_NONSECURE));

  if(NonSecure & ALT_L3_SEC_PERIPHERAL_NAND)
  {
    l3s->nanddata = ALT_L3_SEC_NANDDATA_S_SET(ALT_L3_SEC_NANDDATA_S_E_NONSECURE);
    l3s->nandregs = ALT_L3_SEC_NAND_S_SET(ALT_L3_SEC_NAND_S_E_NONSECURE);
  }
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_NAND)
  {
    l3s->nanddata = ALT_L3_SEC_NANDDATA_S_SET(ALT_L3_SEC_NANDDATA_S_E_SECURE);
    l3s->nandregs = ALT_L3_SEC_NAND_S_SET(ALT_L3_SEC_NAND_S_E_SECURE);
  }

  if(NonSecure & ALT_L3_SEC_PERIPHERAL_QSPI)
  {
    l3s->qspidata = ALT_L3_SEC_QSPIDATA_S_SET(ALT_L3_SEC_QSPIDATA_S_E_NONSECURE);
    l4mp |= ALT_L3_SEC_L4MP_QSPI_SET(ALT_L3_SEC_L4MP_QSPI_E_NONSECURE);
  }
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_QSPI)
  {
    l3s->qspidata = ALT_L3_SEC_QSPIDATA_S_SET(ALT_L3_SEC_QSPIDATA_S_E_SECURE);
    l4mp &= INVERSE(ALT_L3_SEC_L4MP_QSPI_SET(ALT_L3_SEC_L4MP_QSPI_E_NONSECURE));
  }

  if(NonSecure & ALT_L3_SEC_PERIPHERAL_SPI0_SLAVE)
    l4spim |= ALT_L3_SEC_L4SPIM_SPIM0_SET(ALT_L3_SEC_L4SPIM_SPIM0_E_NONSECURE);
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_SPI0_SLAVE)
    l4spim &= INVERSE(ALT_L3_SEC_L4SPIM_SPIM0_SET(ALT_L3_SEC_L4SPIM_SPIM0_E_NONSECURE));
  
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_SPI1_SLAVE)
    l4spim |= ALT_L3_SEC_L4SPIM_SPIM1_SET(ALT_L3_SEC_L4SPIM_SPIM1_E_NONSECURE);
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_SPI1_SLAVE)
    l4spim &= INVERSE(ALT_L3_SEC_L4SPIM_SPIM1_SET(ALT_L3_SEC_L4SPIM_SPIM1_E_NONSECURE));
  
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_SPI0_MASTER)
    main |= ALT_L3_SEC_L4MAIN_SPIS0_SET(ALT_L3_SEC_L4MAIN_SPIS0_E_NONSECURE);
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_SPI0_MASTER)
    main &= INVERSE(ALT_L3_SEC_L4MAIN_SPIS0_SET(ALT_L3_SEC_L4MAIN_SPIS0_E_NONSECURE));
  
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_SPI1_MASTER)
    main |= ALT_L3_SEC_L4MAIN_SPIS1_SET(ALT_L3_SEC_L4MAIN_SPIS1_E_NONSECURE);
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_SPI1_MASTER)
    main &= INVERSE(ALT_L3_SEC_L4MAIN_SPIS1_SET(ALT_L3_SEC_L4MAIN_SPIS1_E_NONSECURE));
  
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_I2C0)
    l4sp |= ALT_L3_SEC_L4SP_I2C0_SET(ALT_L3_SEC_L4SP_I2C0_E_NONSECURE);
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_I2C0)
    l4sp &= INVERSE(ALT_L3_SEC_L4SP_I2C0_SET(ALT_L3_SEC_L4SP_I2C0_E_NONSECURE));
  
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_I2C1)
    l4sp |= ALT_L3_SEC_L4SP_I2C1_SET(ALT_L3_SEC_L4SP_I2C1_E_NONSECURE);
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_I2C1)
    l4sp &= INVERSE(ALT_L3_SEC_L4SP_I2C1_SET(ALT_L3_SEC_L4SP_I2C1_E_NONSECURE));
  
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_I2C2)
    l4sp |= ALT_L3_SEC_L4SP_I2C2_SET(ALT_L3_SEC_L4SP_I2C2_E_NONSECURE);
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_I2C2)
    l4sp &= INVERSE(ALT_L3_SEC_L4SP_I2C2_SET(ALT_L3_SEC_L4SP_I2C2_E_NONSECURE));
  
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_I2C3)
    l4sp |= ALT_L3_SEC_L4SP_I2C3_SET(ALT_L3_SEC_L4SP_I2C3_E_NONSECURE);
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_I2C3)
    l4sp &= INVERSE(ALT_L3_SEC_L4SP_I2C3_SET(ALT_L3_SEC_L4SP_I2C3_E_NONSECURE));
  
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_EMAC0)
    l4mp |= ALT_L3_SEC_L4MP_EMAC0_SET(ALT_L3_SEC_L4MP_EMAC0_E_NONSECURE);
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_EMAC0)
    l4mp &= INVERSE(ALT_L3_SEC_L4MP_EMAC0_SET(ALT_L3_SEC_L4MP_EMAC0_E_NONSECURE));
  
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_EMAC1)
    l4mp |= ALT_L3_SEC_L4MP_EMAC1_SET(ALT_L3_SEC_L4MP_EMAC1_E_NONSECURE);
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_EMAC1)
    l4mp &= INVERSE(ALT_L3_SEC_L4MP_EMAC1_SET(ALT_L3_SEC_L4MP_EMAC1_E_NONSECURE));
  
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_UART0)
    l4sp |= ALT_L3_SEC_L4SP_UART0_SET(ALT_L3_SEC_L4SP_UART0_E_NONSECURE);
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_UART0)
    l4sp &= INVERSE(ALT_L3_SEC_L4SP_UART0_SET(ALT_L3_SEC_L4SP_UART0_E_NONSECURE));
  
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_UART1)
    l4sp |= ALT_L3_SEC_L4SP_UART1_SET(ALT_L3_SEC_L4SP_UART1_E_NONSECURE);
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_UART1)
    l4sp &= INVERSE(ALT_L3_SEC_L4SP_UART1_SET(ALT_L3_SEC_L4SP_UART1_E_NONSECURE));
  
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_GPIO0)
    l4mp |= ALT_L3_SEC_L4MP_GPIO0_SET(ALT_L3_SEC_L4MP_GPIO0_E_NONSECURE);
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_GPIO0)
    l4mp &= INVERSE(ALT_L3_SEC_L4MP_GPIO0_SET(ALT_L3_SEC_L4MP_GPIO0_E_NONSECURE));
  
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_GPIO1)
    l4mp |= ALT_L3_SEC_L4MP_GPIO1_SET(ALT_L3_SEC_L4MP_GPIO1_E_NONSECURE);
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_GPIO1)
    l4mp &= INVERSE(ALT_L3_SEC_L4MP_GPIO1_SET(ALT_L3_SEC_L4MP_GPIO1_E_NONSECURE));
  
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_GPIO2)
    l4mp |= ALT_L3_SEC_L4MP_GPIO2_SET(ALT_L3_SEC_L4MP_GPIO2_E_NONSECURE);
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_GPIO2)
    l4mp &= INVERSE(ALT_L3_SEC_L4MP_GPIO2_SET(ALT_L3_SEC_L4MP_GPIO2_E_NONSECURE));
  
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_SPTIMER0)
    l4sp |= ALT_L3_SEC_L4SP_SPTMR0_SET(ALT_L3_SEC_L4SP_SPTMR0_E_NONSECURE);
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_SPTIMER0)
    l4sp &= INVERSE(ALT_L3_SEC_L4SP_SPTMR0_SET(ALT_L3_SEC_L4SP_SPTMR0_E_NONSECURE));
  
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_SPTIMER1)
    l4sp |= ALT_L3_SEC_L4SP_SPTMR1_SET(ALT_L3_SEC_L4SP_SPTMR1_E_NONSECURE);
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_SPTIMER1)
    l4sp &= INVERSE(ALT_L3_SEC_L4SP_SPTMR1_SET(ALT_L3_SEC_L4SP_SPTMR1_E_NONSECURE));
  
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_OSCTIMER0)
    l4osc1 |= ALT_L3_SEC_L4OSC1_OSC1TMR0_SET(ALT_L3_SEC_L4OSC1_OSC1TMR0_E_NONSECURE);
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_OSCTIMER1)
    l4osc1 &= INVERSE(ALT_L3_SEC_L4OSC1_OSC1TMR0_SET(ALT_L3_SEC_L4OSC1_OSC1TMR0_E_NONSECURE));
  
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_OSCTIMER1)
    l4osc1 |= ALT_L3_SEC_L4OSC1_OSC1TMR0_SET(ALT_L3_SEC_L4OSC1_OSC1TMR1_E_NONSECURE);
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_OSCTIMER1)
    l4osc1 &= INVERSE(ALT_L3_SEC_L4OSC1_OSC1TMR0_SET(ALT_L3_SEC_L4OSC1_OSC1TMR1_E_NONSECURE));

  if(NonSecure & ALT_L3_SEC_PERIPHERAL_WATCHDOG0)
    l4osc1 |= ALT_L3_SEC_L4OSC1_L4WD0_SET(ALT_L3_SEC_L4OSC1_L4WD0_E_NONSECURE);
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_WATCHDOG0)
    l4osc1 &= INVERSE(ALT_L3_SEC_L4OSC1_L4WD0_SET(ALT_L3_SEC_L4OSC1_L4WD0_E_NONSECURE));
 
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_WATCHDOG1)
    l4osc1 |= ALT_L3_SEC_L4OSC1_L4WD1_SET(ALT_L3_SEC_L4OSC1_L4WD1_E_NONSECURE);
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_WATCHDOG1)
    l4osc1 &= INVERSE(ALT_L3_SEC_L4OSC1_L4WD1_SET(ALT_L3_SEC_L4OSC1_L4WD1_E_NONSECURE));
 
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_CLKMGR)
    l4osc1 |= ALT_L3_SEC_L4OSC1_CLKMGR_SET(ALT_L3_SEC_L4OSC1_CLKMGR_E_NONSECURE);
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_CLKMGR)
    l4osc1 &= INVERSE(ALT_L3_SEC_L4OSC1_CLKMGR_SET(ALT_L3_SEC_L4OSC1_CLKMGR_E_NONSECURE));
 
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_OCR)
     l3s->ocram = ALT_L3_SEC_OCRAM_S_SET(ALT_L3_SEC_OCRAM_S_E_NONSECURE);
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_OCR)
     l3s->ocram = ALT_L3_SEC_OCRAM_S_SET(ALT_L3_SEC_OCRAM_S_E_SECURE);
 
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_ACP)
  {
    l3s->acp = ALT_L3_SEC_ACP_S_SET(ALT_L3_SEC_ACP_S_E_NONSECURE);
    l4mp |= ALT_L3_SEC_L4MP_ACPIDMAP_SET(ALT_L3_SEC_L4MP_ACPIDMAP_E_NONSECURE);
  }
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_ACP)
  {
    l3s->acp = ALT_L3_SEC_ACP_S_SET(ALT_L3_SEC_ACP_S_E_SECURE);
    l4mp &= INVERSE((ALT_L3_SEC_L4MP_ACPIDMAP_SET(ALT_L3_SEC_L4MP_ACPIDMAP_E_NONSECURE)));
  }
 
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_ROM)
      l3s->rom = ALT_L3_SEC_ROM_S_SET(ALT_L3_SEC_ROM_S_E_NONSECURE);
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_ROM)
      l3s->rom = ALT_L3_SEC_ROM_S_SET(ALT_L3_SEC_ROM_S_E_SECURE);
 
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_SDRAMCTRL)
  {
    l3s->sdrdata = ALT_L3_SEC_SDRDATA_S_SET(ALT_L3_SEC_SDRDATA_S_E_NONSECURE);
    l4sp |= ALT_L3_SEC_L4SP_SDRREGS_SET(ALT_L3_SEC_L4SP_SDRREGS_E_NONSECURE);
  }
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_SDRAMCTRL)
  {
    l3s->sdrdata = ALT_L3_SEC_SDRDATA_S_SET(ALT_L3_SEC_SDRDATA_S_E_SECURE);
    l4sp &= INVERSE(ALT_L3_SEC_L4SP_SDRREGS_SET(ALT_L3_SEC_L4SP_SDRREGS_E_NONSECURE));
  }
 
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_DAP)
    l4mp |= ALT_L3_SEC_L4MP_DAP_SET(ALT_L3_SEC_L4MP_DAP_E_NONSECURE);
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_DAP)
    l4mp &= INVERSE(ALT_L3_SEC_L4MP_DAP_SET(ALT_L3_SEC_L4MP_DAP_E_NONSECURE));
 
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_RESET)
    l4osc1 |= ALT_L3_SEC_L4OSC1_RSTMGR_SET(ALT_L3_SEC_L4OSC1_RSTMGR_E_NONSECURE);
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_RESET)
    l4osc1 &= INVERSE(ALT_L3_SEC_L4OSC1_RSTMGR_SET(ALT_L3_SEC_L4OSC1_RSTMGR_E_NONSECURE));
 
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_SYSMGR)
    l4osc1 |= ALT_L3_SEC_L4OSC1_SYSMGR_SET(ALT_L3_SEC_L4OSC1_SYSMGR_E_NONSECURE);
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_SYSMGR)
    l4osc1 &= INVERSE(ALT_L3_SEC_L4OSC1_SYSMGR_SET(ALT_L3_SEC_L4OSC1_SYSMGR_E_NONSECURE));
 
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_SCANMGR)
    l4spim |= ALT_L3_SEC_L4SPIM_SCANMGR_SET(ALT_L3_SEC_L4SPIM_SCANMGR_E_NONSECURE);
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_SCANMGR)
    l4spim &= INVERSE(ALT_L3_SEC_L4SPIM_SCANMGR_SET(ALT_L3_SEC_L4SPIM_SCANMGR_E_NONSECURE));
 
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_STMSLAVE)
    l3s->stm = ALT_L3_SEC_STM_S_SET(ALT_L3_SEC_STM_S_E_NONSECURE);
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_STMSLAVE)
    l3s->stm = ALT_L3_SEC_STM_S_SET(ALT_L3_SEC_STM_S_E_SECURE);
 
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_FPGA)
  {
    l3s->hps2fpgaregs = ALT_L3_SEC_H2F_S_SET(ALT_L3_SEC_H2F_S_E_NONSECURE);
    l3s->lwhps2fpgaregs = ALT_L3_SEC_LWH2F_S_SET(ALT_L3_SEC_LWH2F_S_E_NONSECURE);
  }
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_FPGA)
  {
    l3s->hps2fpgaregs = ALT_L3_SEC_H2F_S_SET(ALT_L3_SEC_H2F_S_E_SECURE);
    l3s->lwhps2fpgaregs = ALT_L3_SEC_LWH2F_S_SET(ALT_L3_SEC_LWH2F_S_E_SECURE);
  }
 
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_FPGAMNGR)
  {
    l3s->fpgamgrdata = ALT_L3_SEC_FPGAMGRDATA_S_SET(ALT_L3_SEC_FPGAMGRDATA_S_E_NONSECURE);
    l4mp |= ALT_L3_SEC_L4MP_FPGAMGR_SET(ALT_L3_SEC_L4MP_FPGAMGR_E_NONSECURE);
  }
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_FPGAMNGR)
  {
    l3s->fpgamgrdata = ALT_L3_SEC_FPGAMGRDATA_S_SET(ALT_L3_SEC_FPGAMGRDATA_S_E_SECURE);
    l4mp &= INVERSE(ALT_L3_SEC_L4MP_FPGAMGR_SET(ALT_L3_SEC_L4MP_FPGAMGR_E_NONSECURE));
  }
 
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_GLOBALTIMER)
     scu_ns |= ALT_MPUSCU_NSAC_GLOBAL_NONSECURE;
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_GLOBALTIMER)
     scu_ns &= INVERSE(ALT_MPUSCU_NSAC_GLOBAL_NONSECURE);
 
  if(NonSecure & ALT_L3_SEC_PERIPHERAL_PRIVATETIMER)
    scu_ns |= ALT_MPUSCU_NSAC_PRIVATE_NONSECURE;
  if(SecureOnly & ALT_L3_SEC_PERIPHERAL_PRIVATETIMER)
    scu_ns &= INVERSE(ALT_MPUSCU_NSAC_PRIVATE_NONSECURE);
 
  if(main_o != main )
    l3s->l4main = main;
  if(l4sp_o != l4sp)
    l3s->l4sp = l4sp;
  if(l4mp_o != l4mp)
    l3s->l4mp = l4mp;
  if(l4osc1_o != l4osc1)
    l3s->l4osc1 = l4osc1;
  if(l4spim_o != l4spim)
    l3s->l4spim = l4spim;
  if(scu_ns_o != scu_ns)
    *scu_ns_p = scu_ns;
}
